matrix:
  include:
    - language: java
      jdk: oraclejdk8
      dist: trusty
      before_install: cd restful-web-services/
      install: mvn install
      script: mvn test -B

    - language: node_js
      node_js:
        - 8.9.4
      
      sudo: required

      cache:
        directories:
          - node_modules
      
      addons:
        chrome: stable
        sauce_connect:
        username: "nugyn"
        access_key: "34614a95-e994-42ee-9c65-aa5fd463e769"

      before_install:  
        # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - "npm config set spin false"
      
      before_script:
        - "npm install"

      before_install:
        - "cd frontend/app"

      script: "npm run wdio"

notifications:
  slack: tomyumsept:PvqV1oTyYrS9OKT0hp2kH4TA
  email: false